os:
  - osx

language: c

compiler:
 - gcc
 - clang

env:
 - PY_VERSION=3.5.2

sudo: false

branches:
 only:
  - master
  - /^ci.*$/

addons:
  apt:
    packages:
     - libssl-dev

before_script: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl
  fi
  ls /usr/local/opt/openssl/include
  ls /usr/local/opt/openssl/lib
  wget -P /tmp/ https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/travis_dashboard.cmake

script:
 - ctest -VV -S /tmp/travis_dashboard.cmake

after_script:
 - cat ${TRAVIS_BUILD_DIR}-build/CMakeCache.txt

